
package springboot.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DateServiceImpl", targetNamespace = "http://service.springboot/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DateServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentDate", targetNamespace = "http://service.springboot/", className = "springboot.service.GetCurrentDate")
    @ResponseWrapper(localName = "getCurrentDateResponse", targetNamespace = "http://service.springboot/", className = "springboot.service.GetCurrentDateResponse")
    public String getCurrentDate();

}
