
package springboot.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DateServiceImplService", targetNamespace = "http://service.springboot/", wsdlLocation = "http://localhost:8080/date?wsdl")
public class DateServiceImplService
    extends Service
{

    private final static URL DATESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(springboot.service.DateServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = springboot.service.DateServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/date?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/date?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DateServiceImplService() {
        super(DATESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.springboot/", "DateServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DateServiceImpl
     */
    @WebEndpoint(name = "DateServiceImplPort")
    public DateServiceImpl getDateServiceImplPort() {
        return super.getPort(new QName("http://service.springboot/", "DateServiceImplPort"), DateServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DateServiceImpl
     */
    @WebEndpoint(name = "DateServiceImplPort")
    public DateServiceImpl getDateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.springboot/", "DateServiceImplPort"), DateServiceImpl.class, features);
    }

}
